using System.Text.Json;
using TheKrystalShip.Api.Contracts;
using TheKrystalShip.Api.Data;
using TheKrystalShip.Api.Services.Integrations.WebPush;

namespace TheKrystalShip.Api.Services.Integrations;

/// <summary>
/// Delivers notifications to browsers as Web Push (RFC 8030/8291/8292) — the third
/// <see cref="INotificationProvider"/> beside Slack and the generic webhook.
/// <para>
/// It rides the existing pipeline whole: the bus taps the audit append, the delivery worker applies the
/// per-event rules and the per-<c>(provider,server,event)</c> anti-spam window, and this only has to
/// render and send. That last part matters most for push — a crash-looping server would otherwise wake
/// every phone on the fleet once per watchdog backoff.
/// </para>
/// <para>
/// <b>It differs from its siblings in one structural way.</b> A webhook integration has ONE secret and
/// posts once; push has one credential per user per device and fans out over
/// <see cref="PushSubscriptionStore"/>. So <see cref="TryNormalizeSecret"/> has nothing to normalize —
/// there is no admin-pasted secret here — and the integration row holds only the host's VAPID pair plus
/// the enable/rules the admin does control.
/// </para>
/// </summary>
public sealed class WebPushNotificationProvider(
    PushSubscriptionStore subscriptions,
    WebPushSender sender,
    ApiOptions options,
    ILogger<WebPushNotificationProvider> logger) : INotificationProvider
{
    public string ProviderId => VapidKeyStore.ProviderId;

    private static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);

    public object Describe(IntegrationRecord record) =>
        new WebPushIntegrationView(
            Provider: ProviderId,
            // "Configured" is about the HOST being able to send at all — the key pair. Whether anyone
            // has actually subscribed a device is the panel's own per-user question, not this view's.
            Configured: VapidKeyStore.Read(record) is not null,
            PublicKey: record.Settings.TryGetValue(VapidKeyStore.PublicKeySetting, out string? pk) ? pk : null,
            Enabled: record.Enabled,
            Events: EventViewsFor(record));

    /// <summary>
    /// Always refuses: push has no secret an admin can paste. The VAPID pair is generated by the host
    /// (<see cref="VapidKeyStore"/>) and the per-device credentials are minted by each browser, so a
    /// value arriving here is a mistake rather than a configuration.
    /// </summary>
    public bool TryNormalizeSecret(string raw, out string? normalized, out string? error)
    {
        normalized = null;
        error = "web push has no webhook to set — devices subscribe themselves from the panel, "
              + "and this host's signing key is generated automatically";
        return false;
    }

    public async Task<NotificationTestResult> TestAsync(IntegrationRecord record, CancellationToken ct)
    {
        VapidKeyPair? keys = VapidKeyStore.Read(record);
        if (keys is null)
            return new NotificationTestResult(false, null, null, "no signing key on this host yet — subscribe a device first");

        IReadOnlyList<PushSubscriptionEntity> devices = await subscriptions.AllAsync(ct).ConfigureAwait(false);
        if (devices.Count == 0)
            return new NotificationTestResult(false, null, null, "no devices are subscribed to push on this host");

        byte[] payload = Payload("KGSM Control Panel", "Test notification — push is wired up correctly.", null);
        (int sent, string? firstError) = await FanOutAsync(devices, payload, keys, ct).ConfigureAwait(false);

        // Honest: if nothing landed, say so with the real reason rather than reporting a send we know failed.
        return sent > 0
            ? new NotificationTestResult(true, $"pushed to {sent} of {devices.Count} device(s)", null, null)
            : new NotificationTestResult(false, null, null, firstError ?? "every device rejected the push");
    }

    public async Task<NotificationDeliveryResult> SendAsync(
        NotificationEvent ev, NotificationRule rule, IntegrationRecord record, CancellationToken ct)
    {
        VapidKeyPair? keys = VapidKeyStore.Read(record);
        if (keys is null) return new NotificationDeliveryResult(false, "no VAPID key on this host");

        IReadOnlyList<PushSubscriptionEntity> devices = await subscriptions.AllAsync(ct).ConfigureAwait(false);
        // Not an error: an enabled integration with nobody subscribed simply has nowhere to go.
        if (devices.Count == 0) return new NotificationDeliveryResult(true, null);

        byte[] payload = Payload(Title(ev), ev.Summary, ev.ServerId);
        (int sent, string? firstError) = await FanOutAsync(devices, payload, keys, ct).ConfigureAwait(false);
        return sent > 0
            ? new NotificationDeliveryResult(true, null)
            : new NotificationDeliveryResult(false, firstError ?? "no device accepted the push");
    }

    /// <summary>
    /// Push every device, then record each outcome. A dead subscription (404/410) is deleted on the
    /// spot — a browser that unsubscribed or cleared its data would otherwise be retried forever.
    /// </summary>
    private async Task<(int Sent, string? FirstError)> FanOutAsync(
        IReadOnlyList<PushSubscriptionEntity> devices, byte[] payload, VapidKeyPair keys, CancellationToken ct)
    {
        string subject = VapidSubject();
        int sent = 0;
        string? firstError = null;

        foreach (PushSubscriptionEntity device in devices)
        {
            PushResult result = await sender.SendAsync(device, payload, keys, subject, ct).ConfigureAwait(false);
            switch (result.Outcome)
            {
                case PushOutcome.Accepted:
                    sent++;
                    await subscriptions.RecordOutcomeAsync(device.Endpoint, ok: true, ct).ConfigureAwait(false);
                    break;
                case PushOutcome.Expired:
                    logger.LogInformation("push subscription retired ({Status}): {Reason}", result.Status, result.Error);
                    await subscriptions.ForgetAsync(device.Endpoint, ct).ConfigureAwait(false);
                    break;
                default:
                    firstError ??= result.Error ?? ("HTTP " + result.Status);
                    await subscriptions.RecordOutcomeAsync(device.Endpoint, ok: false, ct).ConfigureAwait(false);
                    break;
            }
        }
        return (sent, firstError);
    }

    /// <summary>
    /// The <c>sub</c> claim: a way to contact whoever runs this server, which push services want from a
    /// sender. This host's own public callback origin is exactly that and is already configured, so no
    /// new setting is invented for it.
    /// </summary>
    private string VapidSubject()
    {
        if (Uri.TryCreate(options.DiscordRedirectUri, UriKind.Absolute, out Uri? uri)
            && (uri.Scheme == Uri.UriSchemeHttps || uri.Scheme == Uri.UriSchemeHttp))
            return uri.GetLeftPart(UriPartial.Authority);
        return "https://localhost";
    }

    /// <summary>The notification body the service worker renders. Deliberately small: a push service
    /// caps the payload, and everything here is already on the panel a tap away.</summary>
    private static byte[] Payload(string title, string body, string? serverId) =>
        JsonSerializer.SerializeToUtf8Bytes(new WebPushPayload(title, body, serverId), Json);

    private static string Title(NotificationEvent ev)
    {
        string server = string.IsNullOrEmpty(ev.ServerId) ? "A server" : ev.ServerId;
        return ev.Action switch
        {
            AuditAction.ServerStart => $"{server} is online",
            AuditAction.ServerRestart => $"{server} restarted",
            AuditAction.ServerStop => $"{server} went offline",
            AuditAction.ServerCrash => $"{server} crashed",
            AuditAction.ServerUpdate => $"{server} was updated",
            AuditAction.ServerUpdateAvailable => $"{server} has an update",
            AuditAction.ServerInstall => $"{server} was installed",
            AuditAction.BackupCreate => $"{server} was backed up",
            _ => server,
        };
    }

    /// <summary>The catalog ⋈ stored-rules overlay, shared with the webhook providers.</summary>
    private static IReadOnlyList<IntegrationEventView> EventViewsFor(IntegrationRecord record)
    {
        var rules = record.Events.ToDictionary(e => e.Id, StringComparer.Ordinal);
        return NotificationCatalog.Events.Select(c =>
        {
            NotificationRule rule = rules.TryGetValue(c.Id, out NotificationRule? r) ? r : NotificationCatalog.DefaultRule(c.Id);
            return new IntegrationEventView(c.Id, c.Title, c.Description, rule.Enabled, rule.Cadence, rule.Ping);
        }).ToList();
    }
}
