using System.Text.Json;
using TheKrystalShip.Api.Contracts;
using TheKrystalShip.Api.Data;
using TheKrystalShip.Api.Services.Integrations.WebPush;

namespace TheKrystalShip.Api.Services.Integrations;

/// <summary>
/// Delivers notifications to browsers as Web Push (RFC 8030/8291/8292) — the third
/// <see cref="INotificationProvider"/> beside Slack and the generic webhook.
/// <para>
/// It rides the existing pipeline whole: the bus taps the audit append, the delivery worker applies the
/// per-event rules and the per-<c>(provider,server,event)</c> anti-spam window, and this only has to
/// render and send. That last part matters most for push — a crash-looping server would otherwise wake
/// every phone on the fleet once per watchdog backoff.
/// </para>
/// <para>
/// <b>It differs from its siblings in one structural way.</b> A webhook integration has ONE secret and
/// posts once; push has one credential per user per device and fans out over
/// <see cref="PushSubscriptionStore"/>. So <see cref="TryNormalizeSecret"/> has nothing to normalize —
/// there is no admin-pasted secret here — and the integration row holds only the host's VAPID pair plus
/// the enable/rules the admin does control.
/// </para>
/// </summary>
public sealed class WebPushNotificationProvider(
    PushSubscriptionStore subscriptions,
    PushPreferenceStore preferences,
    PushSnoozeStore snoozes,
    PushQuietHoursStore quietHours,
    PushActionStore actions,
    WebPushSender sender,
    Aggregation.InstanceCache instances,
    ApiOptions options,
    ILogger<WebPushNotificationProvider> logger) : INotificationProvider
{
    public string ProviderId => VapidKeyStore.ProviderId;

    private static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);

    public object Describe(IntegrationRecord record) =>
        new WebPushIntegrationView(
            Provider: ProviderId,
            // "Configured" is about the HOST being able to send at all — the key pair. Whether anyone
            // has actually subscribed a device is the panel's own per-user question, not this view's.
            Configured: VapidKeyStore.Read(record) is not null,
            PublicKey: record.Settings.TryGetValue(VapidKeyStore.PublicKeySetting, out string? pk) ? pk : null,
            Enabled: record.Enabled,
            Events: EventViewsFor(record));

    /// <summary>
    /// Always refuses: push has no secret an admin can paste. The VAPID pair is generated by the host
    /// (<see cref="VapidKeyStore"/>) and the per-device credentials are minted by each browser, so a
    /// value arriving here is a mistake rather than a configuration.
    /// </summary>
    public bool TryNormalizeSecret(string raw, out string? normalized, out string? error)
    {
        normalized = null;
        error = "web push has no webhook to set — devices subscribe themselves from the panel, "
              + "and this host's signing key is generated automatically";
        return false;
    }

    public async Task<NotificationTestResult> TestAsync(IntegrationRecord record, CancellationToken ct)
    {
        VapidKeyPair? keys = VapidKeyStore.Read(record);
        if (keys is null)
            return new NotificationTestResult(false, null, null, "no signing key on this host yet — subscribe a device first");

        IReadOnlyList<PushSubscriptionEntity> devices = await subscriptions.AllAsync(ct).ConfigureAwait(false);
        if (devices.Count == 0)
            return new NotificationTestResult(false, null, null, "no devices are subscribed to push on this host");

        byte[] payload = Payload(new WebPushPayload(
            "KGSM Control Panel", "Test notification — push is wired up correctly.", null));
        // A test deliberately ignores per-user event choices: it answers "does this channel work at
        // all", which is not a catalog event and not something a person opted out of.
        (int sent, string? firstError) = await FanOutAsync(
            devices, _ => Task.FromResult(payload), keys, wanted: null, ct).ConfigureAwait(false);

        // Honest: if nothing landed, say so with the real reason rather than reporting a send we know failed.
        return sent > 0
            ? new NotificationTestResult(true, $"pushed to {sent} of {devices.Count} device(s)", null, null)
            : new NotificationTestResult(false, null, null, firstError ?? "every device rejected the push");
    }

    public async Task<NotificationDeliveryResult> SendAsync(
        NotificationEvent ev, NotificationRule rule, IntegrationRecord record, CancellationToken ct)
    {
        VapidKeyPair? keys = VapidKeyStore.Read(record);
        if (keys is null) return new NotificationDeliveryResult(false, "no VAPID key on this host");

        IReadOnlyList<PushSubscriptionEntity> devices = await subscriptions.AllAsync(ct).ConfigureAwait(false);
        // Not an error: an enabled integration with nobody subscribed simply has nowhere to go.
        if (devices.Count == 0) return new NotificationDeliveryResult(true, null);

        // The SECOND gate. The worker has already applied the host-wide rule for this event; this
        // narrows it to the people who want it. One read for every account, because the alternative is
        // a query per device.
        IReadOnlyDictionary<(string, string), bool> prefs = await preferences.AllAsync(ct).ConfigureAwait(false);
        // And the THIRD, narrower still: somebody who tapped "snooze" on this exact condition. Scoped
        // to the person and the condition, so it silences one phone about one thing.
        IReadOnlySet<(string, string)> muted = ev.SubjectKey is { Length: > 0 }
            ? await snoozes.ActiveAsync(ct).ConfigureAwait(false)
            : new HashSet<(string, string)>();

        // And the FOURTH: somebody who is asleep. One read for the whole fan-out, keyed by account, and
        // evaluated per device below because the answer depends only on which account owns it.
        DateTimeOffset now = DateTimeOffset.UtcNow;
        IReadOnlyList<PushQuietHoursEntity> windows = await quietHours.ActiveAsync(ct).ConfigureAwait(false);
        var quiet = new Dictionary<string, PushQuietHoursEntity>(StringComparer.Ordinal);
        foreach (PushQuietHoursEntity w in windows)
            if (quietHours.IsQuiet(w, now)) quiet[w.UserSubject] = w;

        bool Wanted(PushSubscriptionEntity d) =>
            // No stored row means yes — see PushPreferenceEntity: the table holds deviations only.
            (!prefs.TryGetValue((d.UserSubject, ev.CatalogId), out bool want) || want)
            && !(ev.SubjectKey is { Length: > 0 } c && muted.Contains((d.UserSubject, c)))
            // Inside a quiet window, only what the person said was worth waking them for. The floor is
            // read off the severity the audit row already carries, so this invents no new judgement about
            // how bad anything is.
            && (!quiet.TryGetValue(d.UserSubject, out PushQuietHoursEntity? window)
                || PushQuietFloor.Passes(ev.Severity, window.MinSeverity));

        (int sent, string? firstError) = await FanOutAsync(
            devices, device => PayloadFor(ev, device, ct), keys, Wanted, ct).ConfigureAwait(false);

        // Nobody wanting this event is a correct outcome, not a failure — reporting it as one would
        // make the worker log an error every time somebody has an event switched off.
        if (sent == 0 && firstError is null) return new NotificationDeliveryResult(true, null);
        return sent > 0
            ? new NotificationDeliveryResult(true, null)
            : new NotificationDeliveryResult(false, firstError);
    }

    /// <summary>
    /// Push every device, then record each outcome. A dead subscription (404/410) is deleted on the
    /// spot — a browser that unsubscribed or cleared its data would otherwise be retried forever.
    /// </summary>
    /// <param name="wanted">Per-device filter — the owner's choice about this event. Null pushes to
    /// every device (a channel test, which no catalog preference applies to).</param>
    /// <param name="payloadFor">The body for one device. Per-device rather than shared because a
    /// notification's buttons are staged against the device that will show them, so two phones
    /// receiving one event carry two different sets of handles.</param>
    private async Task<(int Sent, string? FirstError)> FanOutAsync(
        IReadOnlyList<PushSubscriptionEntity> devices, Func<PushSubscriptionEntity, Task<byte[]>> payloadFor,
        VapidKeyPair keys, Func<PushSubscriptionEntity, bool>? wanted, CancellationToken ct)
    {
        string subject = VapidSubject();
        int sent = 0;
        string? firstError = null;

        foreach (PushSubscriptionEntity device in devices)
        {
            if (wanted is not null && !wanted(device)) continue;
            byte[] payload = await payloadFor(device).ConfigureAwait(false);
            PushResult result = await sender.SendAsync(device, payload, keys, subject, ct).ConfigureAwait(false);
            switch (result.Outcome)
            {
                case PushOutcome.Accepted:
                    sent++;
                    await subscriptions.RecordOutcomeAsync(device.Endpoint, ok: true, ct).ConfigureAwait(false);
                    break;
                case PushOutcome.Expired:
                    logger.LogInformation("push subscription retired ({Status}): {Reason}", result.Status, result.Error);
                    await subscriptions.ForgetAsync(device.Endpoint, ct).ConfigureAwait(false);
                    break;
                default:
                    firstError ??= result.Error ?? ("HTTP " + result.Status);
                    await subscriptions.RecordOutcomeAsync(device.Endpoint, ok: false, ct).ConfigureAwait(false);
                    break;
            }
        }
        return (sent, firstError);
    }

    /// <summary>
    /// The <c>sub</c> claim: a way to contact whoever runs this server, which push services want from a
    /// sender. This host's own public callback origin is exactly that and is already configured, so no
    /// new setting is invented for it.
    /// </summary>
    private string VapidSubject() => options.PublicOrigin ?? "https://localhost";

    /// <summary>The notification body the service worker renders. Deliberately small: a push service
    /// caps the payload, and everything here is already on the panel a tap away.</summary>
    private static byte[] Payload(WebPushPayload payload) =>
        JsonSerializer.SerializeToUtf8Bytes(payload, Json);

    /// <summary>
    /// The body for one device, including whatever buttons it can actually draw.
    /// </summary>
    /// <remarks>
    /// Three things have to hold before an action is staged, and each failing one costs the device its
    /// buttons and nothing else — the notification still arrives and still opens the panel. The event
    /// has to offer an action at all (most do not); the browser has to have reported that it renders
    /// buttons, because staging a capability for a notification that will never show one leaves a live
    /// handle nobody can use; and the row has to name the account's provider-qualified handle, since a
    /// redemption re-resolves the tier from it and cannot do that from a bare subject.
    /// </remarks>
    private async Task<byte[]> PayloadFor(NotificationEvent ev, PushSubscriptionEntity device, CancellationToken ct)
    {
        var payload = new WebPushPayload(
            Title(ev), ev.Summary, ev.ServerId, ev.CatalogId, ev.SubjectKey, options.PublicOrigin);

        IReadOnlyList<PushActionOffer> offers = PushActionCatalog.For(ev, ModerationFor(ev));
        if (offers.Count == 0 || device.MaxActions is not > 0 || string.IsNullOrEmpty(device.UserHandle))
            return Payload(payload);

        var buttons = new List<WebPushAction>();
        foreach (PushActionOffer offer in offers.Take(device.MaxActions.Value))
        {
            string handle = await actions.StageAsync(
                offer.Kind, offer.Target, device.UserHandle!, device.Username, device.Endpoint, offer.Label,
                offer.Subject, ct)
                .ConfigureAwait(false);
            buttons.Add(new WebPushAction(handle, offer.Label));
        }

        return Payload(payload with { Actions = buttons });
    }

    /// <summary>
    /// What the event's game declares it can do to a player, read off the instance the cache already holds.
    /// </summary>
    /// <remarks>
    /// Null for every event that is not about a person, and null when the engine is not readable or does not
    /// know this instance — which the catalog treats as "no moderation", the same as a game that declares
    /// none. That is the deliberate direction to fail in: a button offered on a guess ends with somebody
    /// removed from a game on the strength of an assumption.
    /// </remarks>
    private ModerationCapability? ModerationFor(NotificationEvent ev)
    {
        if (ev.CatalogId != "player_join" || string.IsNullOrEmpty(ev.ServerId)) return null;
        return instances.Roster.TryGetValue(ev.ServerId!, out KGSM.Core.Models.Instance? instance)
            ? Players.ModerationTargetResolver.Describe(instance)
            : null;
    }

    private static string Title(NotificationEvent ev)
    {
        string server = string.IsNullOrEmpty(ev.ServerId) ? "A server" : ev.ServerId;

        // The events the catalog id separates but the action does not. A crash and a give-up are one audit
        // action told apart by severity, and the title is where that distinction has to land — "crashed"
        // under a notification that means "it is not coming back" would be the wrong headline.
        switch (ev.CatalogId)
        {
            case "crash_loop": return $"{server} gave up";
            case "player_join": return $"Someone joined {server}";
            case "server_empty": return $"{server} is empty";

            // These three name no server, so the summary carries the whole subject and the title is the
            // headline — the same shape a host-scope threshold takes.
            case "leaf_down": return "A service went down";
            case "leaf_up": return "A service came back";
            case "awaiting_approval": return "Someone is waiting to be let in";
        }

        return ev.Action switch
        {
            // A threshold event's own summary is the detail (which sensor, which number), so the title is
            // the headline. It says "this host" rather than naming one: a phone reads this off the lock
            // screen with no idea which panel sent it, and the body carries the subject.
            AuditAction.HostThresholdBreach => string.IsNullOrEmpty(ev.ServerId)
                ? "Host threshold crossed"
                : $"{ev.ServerId} threshold crossed",
            AuditAction.HostThresholdClear => string.IsNullOrEmpty(ev.ServerId)
                ? "Host back to normal"
                : $"{ev.ServerId} back to normal",
            AuditAction.ServerStart => $"{server} is online",
            AuditAction.ServerRestart => $"{server} restarted",
            AuditAction.ServerStop => $"{server} went offline",
            AuditAction.ServerCrash => $"{server} crashed",
            AuditAction.ServerUpdate => $"{server} was updated",
            AuditAction.ServerUpdateAvailable => $"{server} has an update",
            AuditAction.ServerInstall => $"{server} was installed",
            AuditAction.BackupCreate => $"{server} was backed up",
            _ => server,
        };
    }

    /// <summary>The catalog ⋈ stored-rules overlay, shared with the webhook providers.</summary>
    private static IReadOnlyList<IntegrationEventView> EventViewsFor(IntegrationRecord record)
    {
        var rules = record.Events.ToDictionary(e => e.Id, StringComparer.Ordinal);
        return NotificationCatalog.Events.Select(c =>
        {
            NotificationRule rule = rules.TryGetValue(c.Id, out NotificationRule? r) ? r : NotificationCatalog.DefaultRule(c.Id);
            return new IntegrationEventView(c.Id, c.Title, c.Description, rule.Enabled, rule.Cadence, rule.Ping);
        }).ToList();
    }
}
